### ISSUE TITLE
Basic Codebase Optimization and Review

### ISSUE THREAD

**Issue by BenCheung0422** [bitsusei/TerraModulus#36]
*Original: https://github.com/MinicraftPlus/minicraft-plus-revived/issues/511, https://github.com/MinicraftPlus/minicraft-plus-revived/issues/580*

## Background

As being a part of game engine rewrite, this should also be included. Many behaviours like instancing and member access controls, impact the structure of the game engine a lot. This should be done at first in a game engine rewrite.

## Details

Besides, many game engine-related structures (like getters and setters) should also be standardized to optimize the game engine and reduce maintenance cost. Purpose reorganization (reorganizing structures according to their purposes) is required. Nearly all classes should be able to be instanced to have controls easier.

For various reasons, the code quality should be improved, including formats, coding practices and error handlings. This includes making good use of standard libraries like Google Guava, Apache Commons, etc., reducing unnecessary blocks of codes and optimizing the codebase. The JavaDoc commenting style should also be united, an example can be taken from https://github.com/MinicraftPlus/minicraft-plus-revived/pull/579. Ideally, any potential errors and exceptions should be caught and handled properly, minimizing the chances getting unhandled errors, uninformative reports and unideal fallbacks/case handlings, thus making it cooperative with the upcoming crash report system (#33). This may need time to be come over.

## Tasks

This task involve optimizing, reorganizing, and reviewing the classes in the codebase. It will be divided into the following five parts, each managed through separate pull requests. Each one following would be made into a pull request when it is the time, checked when merged.

- [ ] Part 1: Methods, Fields and Validation
- [ ] Part 2: Registry and Settings
- [ ] Part 3: Class Categorizing and JSON
- [ ] Part 4: Logging and Crash Report System Part 2
- [ ] Part 5: Performance Optimizations and Display Capacity

**Comment by BenCheung0422** [comment]
The plan has been changed, the repository has been rebuilt with Kotlin with reference and reviews based on Relictus; this is closed as completed.
